### ISSUE TITLE
GitHub Releases is not up-to-date with tags & CHANGELOG.md

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/quota_warning#104]
Similarly to https://github.com/nextcloud/quota_warning/issues/50 but the other way around the https://github.com/nextcloud/quota_warning/releases are not up-to-date with the https://github.com/nextcloud/quota_warning/blob/master/CHANGELOG.md and https://github.com/nextcloud/quota_warning/tags.

Thanks for the continued work @nickvergessen 🙏

**Comment by nickvergessen** [comment]
Releases are now done with automation via the release org:
https://github.com/nextcloud-releases/quota_warning/releases

**Comment by SimJoSt** [comment]
Ah, good Info. That's a bit confusing, when you are not used to that.  
Is there a right up on how that exactly works and what purpose it serves? :)

**Comment by nickvergessen** [comment]
The problem is that in the nextcloud org there are 600+ people with write permissions as we want to be open to collaborators and community. However that also allows to push tags and change them/their attachments. So in theory someone could have removed the release tarball from a tag and so breaking the appstore download link for other users. Unluckily there is no github permission for this so we had to create a secondary organisation where only the maintainer with access to the release key is allowed to push.

The automation is documented in https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/release_automation.html
