### ISSUE TITLE
Single job for all users instead of one job per user

### ISSUE THREAD

**Issue by akhil1508** [nextcloud/quota_warning#203]
- For 10k+ users, the quota warning background jobs take significant amount of time to complete
  - Probably each job run execute adds a constant amount of time to start the job and execute it
- Could running a single time-insensitive job for all users with a duration of 24h be better?
- This would avoid also the extra repair step making updating the app much faster..
- We could use `callForSeenUsers` and `$user->isEnabled()` for this

**Comment by akhil1508** [comment]
@nickvergessen Does this make sense? Would be happy to contribute a PR if it sounds okay..

**Comment by nickvergessen** [comment]
Adjusting the repairstep will make updating faster, yeah.
But a single job for all could be even more problematic as it would run forever.
The problem is setting up the storage of the user to check the quota. This does not get faster if you do it for more users as you need to re-set up the filesystem for each user anyway.

**Comment by nickvergessen** [comment]
That being said, the repair step should only be needed initially. It is listed for install only:
https://github.com/nextcloud/quota_warning/blob/main/appinfo/info.xml#L29-L31

If it retriggers on update, that might be a bug in itself.
Not sure if all background jobs are deleted if they would run while the app is disabled, but if not we could save an app config that initial populating was done and then skip the repairstep in the future.
