### ISSUE TITLE
Chnagelog

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/quota_warning#50]
Where can I find the changelog for the latest versions? CHANGELOG.md seems to be abandoned. Also, there are no details in the release notes.

**Comment by nickvergessen** [comment]
The CHANGELOG.md is up to date.
It's just missing entries for "Release a new version to be compatible with the newest Nextcloud major version".

So:
1.7.0 - Nextcloud 18 compatibility
1.6.0 - Nextcloud 17 compatibility
1.5.0 - Nextcloud 16 compatibility
1.4.0 - Nextcloud 15 compatibility
1.3.0 - Nextcloud 14 compatibility
1.2.0 - Nextcloud 13 compatibility

Other than that there were no changes since 2017

**Comment by nickvergessen** [comment]
Added that to the releases list now:
https://github.com/nextcloud/quota_warning/releases

**Comment by thomas-mc-work** [comment]
You should also mention your efforts in updating the translations.
